In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
df = pd.read_csv("Churn_Modelling.csv")

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [9]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [10]:

df['Exited'].value_counts(normalize=True) * 100

Exited
0    79.63
1    20.37
Name: proportion, dtype: float64

In [11]:
print(df['Geography'].value_counts())
print()
print(df['Gender'].value_counts())

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [12]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [13]:
X = df.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Exited'])
y = df['Exited']

In [14]:
print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (10000, 10)
y shape: (10000,)

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [17]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (8000, 10)
X_test: (2000, 10)
y_train: (8000,)
y_test: (2000,)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_encoded = encoder.fit_transform(X_train[['Geography', 'Gender']])
X_test_encoded = encoder.transform(X_test[['Geography', 'Gender']])

In [20]:
print("Encoded train shape:", X_train_encoded.shape)
print("Encoded test shape:", X_test_encoded.shape)

print("Encoded columns:")
print(encoder.get_feature_names_out())

Encoded train shape: (8000, 5)
Encoded test shape: (2000, 5)
Encoded columns:
['Geography_France' 'Geography_Germany' 'Geography_Spain' 'Gender_Female'
 'Gender_Male']

In [21]:
numerical_features = [
    'CreditScore',
    'Age',
    'Tenure',
    'Balance',
    'NumOfProducts',
    'HasCrCard',
    'IsActiveMember',
    'EstimatedSalary'
]

X_train_num = X_train[numerical_features]
X_test_num = X_test[numerical_features]

In [22]:
import numpy as np

X_train_final = np.hstack([X_train_num.values, X_train_encoded])
X_test_final = np.hstack([X_test_num.values, X_test_encoded])

In [23]:
print("X_train_final shape:", X_train_final.shape)
print("X_test_final shape:", X_test_final.shape)

X_train_final shape: (8000, 13)
X_test_final shape: (2000, 13)

In [24]:
from sklearn.preprocessing import StandardScaler

In [25]:
scaler = StandardScaler()

In [26]:
X_train_scaled = scaler.fit_transform(X_train_final)

In [27]:
X_test_scaled = scaler.transform(X_test_final)

In [28]:
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

X_train_scaled shape: (8000, 13)
X_test_scaled shape: (2000, 13)

In [29]:
print("Mean:", X_train_scaled.mean())
print("Std:", X_train_scaled.std())

Mean: -1.9170989582142704e-16
Std: 0.9999999999999879

In [30]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [32]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
history = model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7870 - loss: 0.4688 - val_accuracy: 0.8244 - val_loss: 0.4254
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8231 - loss: 0.4032 - val_accuracy: 0.8419 - val_loss: 0.3884
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3731 - val_accuracy: 0.8581 - val_loss: 0.3567
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8539 - loss: 0.3524 - val_accuracy: 0.8650 - val_loss: 0.3440
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8564 - loss: 0.3438 - val_accuracy: 0.8675 - val_loss: 0.3343
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3380 - val_accuracy: 0.8662 - val_loss: 0.3350
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3338 - val_accuracy: 0.8675 - val_loss: 0.3335
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8631 - loss: 0.3298 - val_accuracy: 0.8650 - val_loss: 0.3342
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8617 - loss: 0.3273 - val_accuracy: 0.8681 - val_loss: 0.3384
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8653 - loss: 0.3245 - val_accuracy: 0.8637 - val_loss: 0.3374
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8655 - loss: 0.3232 - val_accuracy: 0.8662 - val_loss: 0.3353
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3201 - val_accuracy: 0.8662 - val_loss: 0.3323
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8658 - loss: 0.3191 - val_accuracy: 0.8612 - val_loss: 0.3353
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3175 - val_accuracy: 0.8656 - val_loss: 0.3320
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8691 - loss: 0.3153 - val_accuracy: 0.8662 - val_loss: 0.3350
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8680 - loss: 0.3138 - val_accuracy: 0.8625 - val_loss: 0.3359
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8687 - loss: 0.3102 - val_accuracy: 0.8656 - val_loss: 0.3384
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8680 - loss: 0.3102 - val_accuracy: 0.8681 - val_loss: 0.3337
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8720 - loss: 0.3081 - val_accuracy: 0.8644 - val_loss: 0.3385
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8694 - loss: 0.3071 - val_accuracy: 0.8694 - val_loss: 0.3353
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8737 - loss: 0.3041 - val_accuracy: 0.8594 - val_loss: 0.3407
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8736 - loss: 0.3037 - val_accuracy: 0.8662 - val_loss: 0.3457
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8709 - loss: 0.3030 - val_accuracy: 0.8606 - val_loss: 0.3374
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8750 - loss: 0.3006 - val_accuracy: 0.8675 - val_loss: 0.3371
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8741 - loss: 0.2989 - val_accuracy: 0.8644 - val_loss: 0.3378
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8761 - loss: 0.2975 - val_accuracy: 0.8681 - val_loss: 0.3388
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8747 - loss: 0.2963 - val_accuracy: 0.8587 - val_loss: 0.3459
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8750 - loss: 0.2958 - val_accuracy: 0.8644 - val_loss: 0.3386
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8739 - loss: 0.2944 - val_accuracy: 0.8606 - val_loss: 0.3458
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8766 - loss: 0.2929 - val_accuracy: 0.8681 - val_loss: 0.3477
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8748 - loss: 0.2906 - val_accuracy: 0.8644 - val_loss: 0.3459
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8786 - loss: 0.2889 - val_accuracy: 0.8656 - val_loss: 0.3431
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8797 - loss: 0.2889 - val_accuracy: 0.8725 - val_loss: 0.3454
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8791 - loss: 0.2871 - val_accuracy: 0.8650 - val_loss: 0.3457
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8805 - loss: 0.2848 - val_accuracy: 0.8700 - val_loss: 0.3480
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8808 - loss: 0.2838 - val_accuracy: 0.8662 - val_loss: 0.3506
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8827 - loss: 0.2814 - val_accuracy: 0.8669 - val_loss: 0.3465
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8814 - loss: 0.2814 - val_accuracy: 0.8619 - val_loss: 0.3564
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8820 - loss: 0.2793 - val_accuracy: 0.8619 - val_loss: 0.3538
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8848 - loss: 0.2781 - val_accuracy: 0.8631 - val_loss: 0.3542
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8834 - loss: 0.2776 - val_accuracy: 0.8612 - val_loss: 0.3569
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8834 - loss: 0.2752 - val_accuracy: 0.8612 - val_loss: 0.3600
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8839 - loss: 0.2749 - val_accuracy: 0.8662 - val_loss: 0.3558
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8828 - loss: 0.2739 - val_accuracy: 0.8625 - val_loss: 0.3676
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8831 - loss: 0.2744 - val_accuracy: 0.8637 - val_loss: 0.3698
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8845 - loss: 0.2729 - val_accuracy: 0.8619 - val_loss: 0.3629
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8869 - loss: 0.2722 - val_accuracy: 0.8550 - val_loss: 0.3639
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8888 - loss: 0.2699 - val_accuracy: 0.8606 - val_loss: 0.3628
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8898 - loss: 0.2676 - val_accuracy: 0.8587 - val_loss: 0.3641
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8850 - loss: 0.2692 - val_accuracy: 0.8537 - val_loss: 0.3654

In [34]:
history = model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8895 - loss: 0.2661 - val_accuracy: 0.8537 - val_loss: 0.3660
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8888 - loss: 0.2652 - val_accuracy: 0.8544 - val_loss: 0.3748
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8870 - loss: 0.2646 - val_accuracy: 0.8606 - val_loss: 0.3689
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8914 - loss: 0.2630 - val_accuracy: 0.8612 - val_loss: 0.3708
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8923 - loss: 0.2612 - val_accuracy: 0.8550 - val_loss: 0.3714
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8908 - loss: 0.2603 - val_accuracy: 0.8600 - val_loss: 0.3703
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8906 - loss: 0.2599 - val_accuracy: 0.8569 - val_loss: 0.3744
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8903 - loss: 0.2596 - val_accuracy: 0.8500 - val_loss: 0.3809
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8939 - loss: 0.2550 - val_accuracy: 0.8569 - val_loss: 0.3810
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8906 - loss: 0.2589 - val_accuracy: 0.8575 - val_loss: 0.3768
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8922 - loss: 0.2539 - val_accuracy: 0.8544 - val_loss: 0.3829
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8934 - loss: 0.2560 - val_accuracy: 0.8569 - val_loss: 0.3859
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8961 - loss: 0.2533 - val_accuracy: 0.8575 - val_loss: 0.3910
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8948 - loss: 0.2534 - val_accuracy: 0.8612 - val_loss: 0.3874
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8961 - loss: 0.2519 - val_accuracy: 0.8587 - val_loss: 0.3891
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8963 - loss: 0.2509 - val_accuracy: 0.8562 - val_loss: 0.3853
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8961 - loss: 0.2500 - val_accuracy: 0.8562 - val_loss: 0.3932
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8952 - loss: 0.2486 - val_accuracy: 0.8537 - val_loss: 0.3901
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8972 - loss: 0.2481 - val_accuracy: 0.8612 - val_loss: 0.3993
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8972 - loss: 0.2468 - val_accuracy: 0.8537 - val_loss: 0.3942
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9002 - loss: 0.2448 - val_accuracy: 0.8569 - val_loss: 0.3965
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8972 - loss: 0.2451 - val_accuracy: 0.8531 - val_loss: 0.3918
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8973 - loss: 0.2468 - val_accuracy: 0.8406 - val_loss: 0.4123
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8980 - loss: 0.2451 - val_accuracy: 0.8419 - val_loss: 0.4033
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8994 - loss: 0.2406 - val_accuracy: 0.8531 - val_loss: 0.3987
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8997 - loss: 0.2425 - val_accuracy: 0.8487 - val_loss: 0.4011
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8958 - loss: 0.2432 - val_accuracy: 0.8413 - val_loss: 0.4118
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8967 - loss: 0.2412 - val_accuracy: 0.8587 - val_loss: 0.4010
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9008 - loss: 0.2381 - val_accuracy: 0.8544 - val_loss: 0.4058
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9034 - loss: 0.2383 - val_accuracy: 0.8462 - val_loss: 0.4072
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8995 - loss: 0.2361 - val_accuracy: 0.8500 - val_loss: 0.4070
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9013 - loss: 0.2386 - val_accuracy: 0.8512 - val_loss: 0.4075
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9016 - loss: 0.2356 - val_accuracy: 0.8562 - val_loss: 0.4233
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9019 - loss: 0.2351 - val_accuracy: 0.8450 - val_loss: 0.4181
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9017 - loss: 0.2350 - val_accuracy: 0.8494 - val_loss: 0.4132
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9028 - loss: 0.2350 - val_accuracy: 0.8469 - val_loss: 0.4182
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9014 - loss: 0.2340 - val_accuracy: 0.8381 - val_loss: 0.4272
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9005 - loss: 0.2321 - val_accuracy: 0.8444 - val_loss: 0.4234
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9047 - loss: 0.2293 - val_accuracy: 0.8456 - val_loss: 0.4210
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9019 - loss: 0.2269 - val_accuracy: 0.8375 - val_loss: 0.4232
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9047 - loss: 0.2278 - val_accuracy: 0.8562 - val_loss: 0.4259
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9055 - loss: 0.2282 - val_accuracy: 0.8456 - val_loss: 0.4246
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9047 - loss: 0.2271 - val_accuracy: 0.8450 - val_loss: 0.4285
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9064 - loss: 0.2277 - val_accuracy: 0.8363 - val_loss: 0.4286
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9081 - loss: 0.2264 - val_accuracy: 0.8313 - val_loss: 0.4340
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9031 - loss: 0.2244 - val_accuracy: 0.8431 - val_loss: 0.4304
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9077 - loss: 0.2258 - val_accuracy: 0.8438 - val_loss: 0.4305
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9044 - loss: 0.2238 - val_accuracy: 0.8456 - val_loss: 0.4280
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9087 - loss: 0.2237 - val_accuracy: 0.8363 - val_loss: 0.4325
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9070 - loss: 0.2242 - val_accuracy: 0.8388 - val_loss: 0.4479

In [35]:
test_loss, test_accuracy = model.evaluate(
    X_test_scaled,
    y_test
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8305 - loss: 0.4417
Test Loss: 0.44165554642677307
Test Accuracy: 0.8305000066757202

In [36]:
y_pred_prob = model.predict(X_test_scaled)

print(y_pred_prob[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step
[[0.00738005]
 [0.01701539]
 [0.00059337]
 [0.07970046]
 [0.08942199]]

In [37]:
y_pred_prob = model.predict(X_test_scaled)

print(y_pred_prob[:5])

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.00738005]
 [0.01701539]
 [0.00059337]
 [0.07970046]
 [0.08942199]]

In [38]:
y_pred = (y_pred_prob >= 0.5).astype(int)

print(y_pred[:5].ravel())

[0 0 0 0 0]

In [39]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print(cm)

[[1457  136]
 [ 203  204]]

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.91      0.90      1593
           1       0.60      0.50      0.55       407

    accuracy                           0.83      2000
   macro avg       0.74      0.71      0.72      2000
weighted avg       0.82      0.83      0.82      2000

In [41]:
baseline_accuracy = test_accuracy
baseline_f1 = 0.55
baseline_recall = 0.50

In [42]:
print("Baseline Accuracy:", baseline_accuracy)
print("Baseline F1:", baseline_f1)
print("Baseline Recall:", baseline_recall)

Baseline Accuracy: 0.8305000066757202
Baseline F1: 0.55
Baseline Recall: 0.5

In [45]:
from tensorflow.keras.callbacks import EarlyStopping

In [44]:
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [46]:
model_es = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [47]:
model_es.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [48]:
history_es = model_es.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7875 - loss: 0.4683 - val_accuracy: 0.8194 - val_loss: 0.4263
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8233 - loss: 0.4080 - val_accuracy: 0.8413 - val_loss: 0.3890
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8425 - loss: 0.3767 - val_accuracy: 0.8594 - val_loss: 0.3578
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8487 - loss: 0.3575 - val_accuracy: 0.8669 - val_loss: 0.3455
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8533 - loss: 0.3502 - val_accuracy: 0.8681 - val_loss: 0.3394
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8570 - loss: 0.3450 - val_accuracy: 0.8687 - val_loss: 0.3356
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8591 - loss: 0.3415 - val_accuracy: 0.8669 - val_loss: 0.3401
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8614 - loss: 0.3401 - val_accuracy: 0.8694 - val_loss: 0.3343
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8581 - loss: 0.3360 - val_accuracy: 0.8687 - val_loss: 0.3323
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8611 - loss: 0.3340 - val_accuracy: 0.8675 - val_loss: 0.3312
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8627 - loss: 0.3310 - val_accuracy: 0.8675 - val_loss: 0.3325
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8630 - loss: 0.3284 - val_accuracy: 0.8669 - val_loss: 0.3327
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3273 - val_accuracy: 0.8656 - val_loss: 0.3320
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3245 - val_accuracy: 0.8687 - val_loss: 0.3296
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8669 - loss: 0.3222 - val_accuracy: 0.8656 - val_loss: 0.3316
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3214 - val_accuracy: 0.8644 - val_loss: 0.3326
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8686 - loss: 0.3182 - val_accuracy: 0.8637 - val_loss: 0.3310
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3186 - val_accuracy: 0.8612 - val_loss: 0.3320
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8675 - loss: 0.3147 - val_accuracy: 0.8669 - val_loss: 0.3326

In [49]:
test_loss_es, test_accuracy_es = model_es.evaluate(
    X_test_scaled,
    y_test
)

print("Early Stopping Test Loss:", test_loss_es)
print("Early Stopping Test Accuracy:", test_accuracy_es)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8595 - loss: 0.3448
Early Stopping Test Loss: 0.34483227133750916
Early Stopping Test Accuracy: 0.859499990940094

In [50]:
y_pred_prob_es = model_es.predict(X_test_scaled)
y_pred_es = (y_pred_prob_es >= 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [51]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_es))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      1593
           1       0.79      0.42      0.55       407

    accuracy                           0.86      2000
   macro avg       0.83      0.70      0.73      2000
weighted avg       0.85      0.86      0.84      2000

In [52]:
model_dropout = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [53]:
model_dropout.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [54]:
history_dropout = model_dropout.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7909 - loss: 0.4857 - val_accuracy: 0.8100 - val_loss: 0.4376
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8062 - loss: 0.4418 - val_accuracy: 0.8375 - val_loss: 0.4190
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8178 - loss: 0.4240 - val_accuracy: 0.8406 - val_loss: 0.3973
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8302 - loss: 0.4018 - val_accuracy: 0.8537 - val_loss: 0.3707
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8364 - loss: 0.3901 - val_accuracy: 0.8606 - val_loss: 0.3594

In [55]:
test_loss_dropout, test_accuracy_dropout = model_dropout.evaluate(
    X_test_scaled,
    y_test
)

print("Dropout Test Loss:", test_loss_dropout)
print("Dropout Test Accuracy:", test_accuracy_dropout)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8075 - loss: 0.4337
Dropout Test Loss: 0.433694064617157
Dropout Test Accuracy: 0.8075000047683716

In [56]:
y_pred_prob_dropout = model_dropout.predict(X_test_scaled)
y_pred_dropout = (y_pred_prob_dropout >= 0.5).astype(int)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [57]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_dropout))

              precision    recall  f1-score   support

           0       0.81      0.99      0.89      1593
           1       0.66      0.11      0.19       407

    accuracy                           0.81      2000
   macro avg       0.74      0.55      0.54      2000
weighted avg       0.78      0.81      0.75      2000

In [58]:
learning_rate = 0.0005

In [59]:
model_lr = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(13,)),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

optimizer_lr = tf.keras.optimizers.Adam(
    learning_rate=0.0005
)

model_lr.compile(
    optimizer=optimizer_lr,
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history_lr = model_lr.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stopping]
)

Epoch 1/50

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7817 - loss: 0.4909 - val_accuracy: 0.8044 - val_loss: 0.4321
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8148 - loss: 0.4200 - val_accuracy: 0.8344 - val_loss: 0.4047
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8311 - loss: 0.3954 - val_accuracy: 0.8438 - val_loss: 0.3859
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8436 - loss: 0.3766 - val_accuracy: 0.8550 - val_loss: 0.3638
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8489 - loss: 0.3632 - val_accuracy: 0.8612 - val_loss: 0.3512

In [60]:
test_loss_lr, test_accuracy_lr = model_lr.evaluate(
    X_test_scaled,
    y_test
)

print("Learning Rate Test Loss:", test_loss_lr)
print("Learning Rate Test Accuracy:", test_accuracy_lr)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8000 - loss: 0.4374
Learning Rate Test Loss: 0.4374208152294159
Learning Rate Test Accuracy: 0.800000011920929

In [61]:
y_pred_prob_lr = model_lr.predict(X_test_scaled)
y_pred_lr = (y_pred_prob_lr >= 0.5).astype(int)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lr))

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step
              precision    recall  f1-score   support

           0       0.80      1.00      0.89      1593
           1       0.89      0.02      0.04       407

    accuracy                           0.80      2000
   macro avg       0.84      0.51      0.46      2000
weighted avg       0.82      0.80      0.72      2000

In [62]:
results = {
    "Baseline": {
        "Accuracy": baseline_accuracy,
        "Recall": 0.50,
        "F1": 0.55
    },
    "Early Stopping": {
        "Accuracy": test_accuracy_es,
        "Recall": 0.42,
        "F1": 0.55
    },
    "Dropout": {
        "Accuracy": test_accuracy_dropout,
        "Recall": 0.11,
        "F1": 0.19
    },
    "Learning Rate 0.0005": {
        "Accuracy": test_accuracy_lr,
        "Recall": 0.02,
        "F1": 0.04
    }
}

results_df = pd.DataFrame(results).T
print(results_df)

                      Accuracy  Recall    F1
Baseline                0.8305    0.50  0.55
Early Stopping          0.8595    0.42  0.55
Dropout                 0.8075    0.11  0.19
Learning Rate 0.0005    0.8000    0.02  0.04